baseURL = 'https://artsofbaniya.com/'
languageCode = 'en-us'
title = '★✰ Aditya Agarwal ★✰ '
author = 'Aditya Agarwal'
theme = 'hugo-bearblog'

publishDir = 'docs'

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[Social]
  twitter = "artsofbaniya"